export default function TradingViewIDLookup(cryptoSymbol) {
	const TradingViewCryptoIDDatabase = [
		{ cryptoSymbol: 'BTC',  TradingViewCryptoID: 'COINBASE:BTCUSD' },
		{ cryptoSymbol: 'ETH',  TradingViewCryptoID: 'COINBASE:ETHUSD'  },
		{ cryptoSymbol: 'XRP',  TradingViewCryptoID: 'BITFINEX:XRPUSD'  },
		{ cryptoSymbol: 'BCH',  TradingViewCryptoID: 'BITTREX:BCCUSDT'  },
		{ cryptoSymbol: 'LTC',  TradingViewCryptoID: 'COINBASE:LTCUSD'  },
		{ cryptoSymbol: 'NEO',  TradingViewCryptoID: 'BINANCE:NEOUSDT'  },
		{ cryptoSymbol: 'XLM',  TradingViewCryptoID: 'KRAKEN:XLMUSD'    },
		{ cryptoSymbol: 'ADA',  TradingViewCryptoID: 'BITTREX:ADAUSDT'  },
		{ cryptoSymbol: 'XMR',  TradingViewCryptoID: 'BITFINEX:XMRUSD'  },
		{ cryptoSymbol: 'EOS',  TradingViewCryptoID: 'BITFINEX:EOSUSD'  },
		{ cryptoSymbol: 'DASH', TradingViewCryptoID: 'BITTREX:DASHUSD'  },
		{ cryptoSymbol: 'MIOTA', TradingViewCryptoID: 'BINANCE:IOTAUSD'  },
		{ cryptoSymbol: 'XEM',  TradingViewCryptoID: 'POLONIEX:XEMUSD'  },
		{ cryptoSymbol: 'TRX',  TradingViewCryptoID: 'BINANCE:TRONUSD'  },
		{ cryptoSymbol: 'ETC',  TradingViewCryptoID: 'BITFINEX:ETCUSD'  },
		{ cryptoSymbol: 'USDT', TradingViewCryptoID: 'KRAKEN:USDTUSD'   },
		{ cryptoSymbol: 'VEN',  TradingViewCryptoID: 'BINANCE:VENUSD'   },
		{ cryptoSymbol: 'NANO', TradingViewCryptoID: 'BINANCE:NANOBTC'  }, //BTC
		{ cryptoSymbol: 'LSK',  TradingViewCryptoID: 'BINANCE:LSKUSD'   },
		{ cryptoSymbol: 'OMG',  TradingViewCryptoID: 'BINANCE:OMGUSD'   },
		{ cryptoSymbol: 'BTG',  TradingViewCryptoID: 'BITFINEX:BTGUSD'  },
		{ cryptoSymbol: 'QTUM', TradingViewCryptoID: 'BINANCE:QTUMUSD'  },
		{ cryptoSymbol: 'ZEC',  TradingViewCryptoID: 'BITTREX:ZECUSD'   },
		{ cryptoSymbol: 'ICX',  TradingViewCryptoID: 'BINANCE:ICXUSD'   },
		{ cryptoSymbol: 'BNB',  TradingViewCryptoID: 'BINANCE:BNBUSD'   },
		{ cryptoSymbol: 'DGD',  TradingViewCryptoID: 'BINANCE:DGDUSD'   },
		{ cryptoSymbol: 'STEEM',TradingViewCryptoID: 'BITTREX:STEEMUSD' },
		{ cryptoSymbol: 'BCN',TradingViewCryptoID:   'POLONIEX:BCNUSD'  },
		{ cryptoSymbol: 'PPT',TradingViewCryptoID:   'BINANCE:PPTUSD'   },
		{ cryptoSymbol: 'WAVES',TradingViewCryptoID:  'BITTREX:WAVESUSD' },
		{ cryptoSymbol: 'XVG',TradingViewCryptoID:   'BITTREX:XVGUSD'    },
		{ cryptoSymbol: 'STRAT',TradingViewCryptoID:  'BITTREX:STRATUSD' },
		{ cryptoSymbol: 'MKR', TradingViewCryptoID:   ''    },
		{ cryptoSymbol: 'RHOC', TradingViewCryptoID:  ''    },
		{ cryptoSymbol: 'SNT',TradingViewCryptoID:  'BITFINEX:SNTUSD'    },
		{ cryptoSymbol: 'DOGE',TradingViewCryptoID:  'BITTREX:DOGEUSD'   },
		{ cryptoSymbol: 'SC',TradingViewCryptoID:  'BITTREX:SCUSD'       },
		{ cryptoSymbol: 'BTS',TradingViewCryptoID:  'POLONIEX:BTSUSD'    },
		{ cryptoSymbol: 'DCR',TradingViewCryptoID:  'BITTREX:DCRUSD'     },
		{ cryptoSymbol: 'AE',TradingViewCryptoID:  'BINANCE:AEBTC'       }, //BTC
		{ cryptoSymbol: 'WTC',TradingViewCryptoID:  'BINANCE:WTCUSD'     },
		{ cryptoSymbol: 'REP',TradingViewCryptoID:  'BITTREX:REPUSD'     },
		{ cryptoSymbol: 'BTM',TradingViewCryptoID:  'POLONIEX:BTMUSD'    }, //wrong symbol
		{ cryptoSymbol: 'KMD',TradingViewCryptoID:  'BINANCE:KMDUSD'     },
		{ cryptoSymbol: 'ZRX',TradingViewCryptoID:  'POLONIEX:ZRXUSD'    },
		{ cryptoSymbol: 'VERI',TradingViewCryptoID:  'HITBTC:VERIUSD'    },
		{ cryptoSymbol: 'ETN',TradingViewCryptoID:  ''   },
		{ cryptoSymbol: 'ARK',TradingViewCryptoID:  'BITTREX:ARKUSD'     },
		{ cryptoSymbol: 'CNX',TradingViewCryptoID:  ''   },
		{ cryptoSymbol: 'KCS',TradingViewCryptoID:  ''   },
		{ cryptoSymbol: 'ARDR',TradingViewCryptoID:  'BITTREX:ARDRUSD'   },
		{ cryptoSymbol: 'ZIL',TradingViewCryptoID:  'BINANCE:ZILBTC'   }, //BTC
		{ cryptoSymbol: 'SYS',TradingViewCryptoID:  'BITTREX:SYSUSD'   },
		{ cryptoSymbol: 'BAT',TradingViewCryptoID:  'BITTREX:BATUSD'   },
		{ cryptoSymbol: 'HSR',TradingViewCryptoID:  'BINANCE:HSRBTC'   }, //BTC
		{ cryptoSymbol: 'GNT',TradingViewCryptoID:  'BITTREX:GNTUSD'   },
		{ cryptoSymbol: 'DRGN',TradingViewCryptoID:  ''   },
		{ cryptoSymbol: 'DGB',TradingViewCryptoID:  'BITTREX:DGBUSD'   },
		{ cryptoSymbol: 'PIVX',TradingViewCryptoID:  'BITTREX:PIVXUSD'   },
		{ cryptoSymbol: 'GAS',TradingViewCryptoID:  'BINANCE:GASUSD'   },
		{ cryptoSymbol: 'MONA',TradingViewCryptoID:  'BITTREX:MONAUSD'   },
		{ cryptoSymbol: 'ETHOS',TradingViewCryptoID:  ''   },
		{ cryptoSymbol: 'AION',TradingViewCryptoID:  'BINANCE:AIONUSD'   },
		{ cryptoSymbol: 'QASH',TradingViewCryptoID:  ''   },
		{ cryptoSymbol: 'FCT',TradingViewCryptoID:  'BITTREX:FCTUSD'   },
		{ cryptoSymbol: 'NAS',TradingViewCryptoID:  ''   },
		{ cryptoSymbol: 'LRC',TradingViewCryptoID:  'BINANCE:LRCUSD'   },
		{ cryptoSymbol: 'FUN',TradingViewCryptoID:  'BINANCE:FUNUSD'   },
		{ cryptoSymbol: 'GBYTE',TradingViewCryptoID:  'BITTREX:GBYTEUSD'   },
		{ cryptoSymbol: 'R',TradingViewCryptoID:  ''   },
		{ cryptoSymbol: 'ELF',TradingViewCryptoID:  'BINANCE:AELFUSD'   },
		{ cryptoSymbol: 'PART',TradingViewCryptoID:  'BITTREX:PARTUSD'   },
		{ cryptoSymbol: 'DCN',TradingViewCryptoID:  ''   },
		{ cryptoSymbol: 'RDD',TradingViewCryptoID:  'BITTREX:RDDUSD'   },
		{ cryptoSymbol: 'XVC',TradingViewCryptoID:  'BITTREX:XVCUSD'   },
		{ cryptoSymbol: 'GXS',TradingViewCryptoID:  'BINANCE:GXSUSD'   },
		{ cryptoSymbol: 'KIN',TradingViewCryptoID:  ''   },
		{ cryptoSymbol: 'LINK',TradingViewCryptoID:  'BINANCE:LINKUSD'   },
		{ cryptoSymbol: 'KNC',TradingViewCryptoID:  'BINANCE:KNCUSD'   },
		{ cryptoSymbol: 'SLT',TradingViewCryptoID:  ''   },
		{ cryptoSymbol: 'POLY',TradingViewCryptoID:  ''   },
		{ cryptoSymbol: 'NXT',TradingViewCryptoID:  'BITTREX:NXT'   },
		{ cryptoSymbol: 'IOST',TradingViewCryptoID:  'BINANCE:IOST'   },
		{ cryptoSymbol: 'NXS',TradingViewCryptoID:  'BITTREX:NXS'   },
		{ cryptoSymbol: 'BNT',TradingViewCryptoID:  'BITTREX:BNT'   },
		{ cryptoSymbol: 'DENT',TradingViewCryptoID:  ''   },
		{ cryptoSymbol: 'POWR',TradingViewCryptoID:  'BINANCE:POWR'   },
		{ cryptoSymbol: 'SMART',TradingViewCryptoID:  ''   },
		{ cryptoSymbol: 'ICN',TradingViewCryptoID:  'KRAKEN:ICNUSD'   },
		{ cryptoSymbol: 'NEBL',TradingViewCryptoID:  'BINANCE:NEBLUSD'   },
		{ cryptoSymbol: 'EMC',TradingViewCryptoID:  'HITBTC:EMCUSD'   },
		{ cryptoSymbol: 'SRN',TradingViewCryptoID:  'BITTREX:SRNBTC'   }, //BTC
		{ cryptoSymbol: 'AGI',TradingViewCryptoID:  ''   },
		{ cryptoSymbol: 'BTX',TradingViewCryptoID:  ''   },
		{ cryptoSymbol: 'PAY',TradingViewCryptoID:  'BITTREX:PAYUSD'   },
		{ cryptoSymbol: 'ENG',TradingViewCryptoID:  'BINANCE:ENGUSD'   },
		{ cryptoSymbol: 'REQ',TradingViewCryptoID:  'BINANCE:REQUSD'   },
		{ cryptoSymbol: 'PLR',TradingViewCryptoID:  ''   },
		{ cryptoSymbol: 'STORJ',TradingViewCryptoID:  'BITTREX:STORJUSD'   },
		{ cryptoSymbol: 'MAID',TradingViewCryptoID:  'BITTREX:MAIDUSD'   },

	];


	for(let e = 0; e<TradingViewCryptoIDDatabase.length; e++) {
		if(TradingViewCryptoIDDatabase[e].cryptoSymbol === cryptoSymbol) {
			return TradingViewCryptoIDDatabase[e].TradingViewCryptoID;
		}
	}
}